# Putting `magic` into your literature review

Let us assume that you are interested in quickly getting a sense of which papers are important in a particular field of study. In practical terms, you have a couple of papers that you found via Google Scholar, and now you want to know which other papers you should also read.

For demonstration purposes, let's say that you wish to study basic emotions and emotion coherence. Someone recommended that you read Paul Ekman's chapter on basic emotions (1999) and you found an interesting paper on emotion coherence by Iris Mauss and her colleagues (2005) on Google Scholar.

The `magic` package helps you to systematically harvest citations from these papers to get an overview of related research and can guide your literature review by highlighting other papers that you probably should also read.

# Creating entries in the literature review database
At the moment, `magic` requires a high level of instruction from the user (although part of this can be automated in the future). The first step is to let `magic` know which paper you are currently reading. To accomplish this, we will use `magicPaper` function.

## Creating a new paper with `magicPaper`
The only required argument for `magicPaper` is a __citation key__ (or citekey for short). Each paper must be uniquely identified, so that we know which papers cite which other papers. The citekey will be in the format of first author's family name and publication year, similar to the APA style in-text citations. Since our first paper to be read is by Ekman, the citekey will be `ekman1999`. Notice that there are no spaces, hyphenation is removed, and special characters are replaced with their basic equivalents (i.e., ö = o).

Thus, to create a new paper in the literature review database, you can simply type:
```
magicPaper("ekman1999")
```

However, it would also be nice to include the paper title in the database entry, wouldn't it? This can be done by typing:
```
magicPaper("ekman1999", "Basic Emotions", update = TRUE)
```
The `update = TRUE` argument indicates that you are not creating a new paper, just updating an existing one.

Since we will be needing the citekey `ekman1999` a lot while creating citations originating from his paper, let's store it for easy use:
```
myPDF <- "ekman1999"
```
This allows us to use `myPDF` instead of having to type `ekman1999` every time we wish to make a citation.

## Creating citations with `magicCite`
Now that the paper by Ekman is in our database and the citekey handily available, we can start reading the paper itself. Currently, there are no automated parsing functions in `magic` (yet) to identify the citations for you, so you need to read the paper carefully, sentence by sentence (as a diligent academic should anyway). As you read the PDF, whenever you encounter a sentence that cites another paper, copy it to clipboard. The first sentence in Ekman's paper has a self-citation:
_"In this chapter I consolidate my previous writings about basic emotions (Ekman, 1984,1992a, 1992b) and introduce a few changes in my thinking."_ Let's copy it to clipboard, then!

Since this sentence actually makes three citations, we need to use the `magicCite` function three times, like this:
```
magicCite(from = myPDF, 
          to <- "Ekman1984",
          sentence <- "In this chapter I consolidate my previous writings about basic emotions (Ekman1984) and introduce a few changes in my thinking.",
          section <- "i"
)

magicCite(from = myPDF, 
          to <- "Ekman1992a",
          sentence <- "In this chapter I consolidate my previous writings about basic emotions (Ekman1984) and introduce a few changes in my thinking.",
          section <- "i"
)

magicCite(from = myPDF, 
          to <- "Ekman1992b",
          sentence <- "In this chapter I consolidate my previous writings about basic emotions (Ekman1984) and introduce a few changes in my thinking.",
          section <- "i"
)
```

The `from` argument indicates the source document making the citation (`ekman1999` in our case, stored in the `myPDF` variable). The `to` argument is the target of the citation, `sentence` is the textual context in which the citation occurs, and the `section` indicates whether the citation occurs in the __i__ntroduction, __m__ethod, __r__esults, or __d__iscussion (as indicated by the first letter of the section heading).

Thus, reading the entire paper, your script would include a long list of `magicCite` functions (see a [full example for `ekman1999`](https://github.com/vanderlowe/magic/blob/master/inst/examples/ekman1999.R)).

# Making sense of the literature in the database

After entering citations from just two papers, we can already gain valuable insight about citation trends to guide our literature review. The function `magicSynopsis` can be used to get a a brief summary of the paper. Let us start with learning about citation patterns in `ekman1999`. 
```
magicSynopsis("ekman1999")
```

The function provides the following output:
```
Most frequently cited articles in ekman1999:
1) ohman1986 (4 times)
2) lazarus1991 (3 times)
3) stein1992 (3 times)
4) darwin1872 (2 times)
5) ekman1975 (2 times)
6) ekman1984 (2 times)
7) johnsonlaird1992 (2 times)
8) levenson1990 (2 times)
9) tooby1990 (2 times)
```
It appears that Ekman made a reference to a paper `ohman1986` four times, suggesting that it might be relevant to us, too. Let's take a look at this paper, then.
```
magicSynopsis("ohman1986")
```
The output of the command is as follows:
```
ekman1999 [cited 4 time(s)]:
Ohman's (1986) analysis of fear is relevant to these complexities. He distinguishes fear of animals, fear of people, and fear of inanimate objects, suggesting that different actions may have evolved for fear of a predator as compared to social fears.  Similar views have since been described by Zajonc (1985), Öhman (1986), Leventhal & Scherer (1987) and Buck (1985). In all likelihood, not enough is given for automatic appraisal to ever operate without considerable amplification and detailing through social learning (see, especially, Öhman, 1986 on this point).  Öhman (1986) describes how both evolution and social learning contribute to the establishment of those events which call forth one or another emotion.

Most frequent citation words ohman1986:
fear 
```
Well, look at that! A rather nice summary of `ohman1984`, in the words of Dr. Paul Ekman himself. Seems like `ohman1984` is a paper about biological and social influences on the emotion of fear. Peeking into the PDF, we find out that the title of `Ohman1984` is _"Face the beast and fear the face: animal and social fears as prototypes for evolutionary analyses of emotion"_, which indeed matches the synopsis.

(As a sidenote, the output for `ohman1986` is slightly different from what we saw before, because it was cited by `ekman1999` whereas `ekman1999` was not cited by `Mauss2005`, the only other paper in this example. Because `ekman1999` was a source, but not the target of citations, output for `magicSynopsis("ohman1984")` was different from `magicSynopsis("ekman1999")`. For papers that are both target and sources of citations, the output combines both types of information.)

In `ekman1999`, the second most cited paper is `lazarus1991`, so let's look at that, too. The output of `magicSynopsis("lazarus1991")` is:
```
ekman1999 [cited 3 time(s)]:
Lazarus (1991) talks of "common adaptational" tasks as these are appraised and configured into core relational themes" (p. 202) and gives examples of facing an immediate danger, experiencing an irrevocable loss, progressing towards the realization of a goal, etc. Lazarus (1991) cites this same study to argue his rather similar view. Although he emphasizes what he calls "meaning analysis", Lazarus also describes common antecedent events. Lazarus (1991), has a similar but in some ways different account, describing what he calls the "core relational theme" unique to the appraisal of each emotion.

mauss2005 [cited 6 time(s)]:
For many theorists, a defining feature of emotion is response coherence (e.g., Ekman, 1972, 1992; Lazarus, 1991; Levenson, 1994; Scherer, 1984; Tomkins, 1962).  Most, but not all, of these theorists have taken a functional perspective, proposing that by imposing coherence across response systems, emotions facilitate the organism’s response to environmental demands (e.g., Ekman, 1992; Lazarus, 1991; Levenson, 1994; Plutchik, 1980; Witherington, Campos, & Hertentein, 2001).  Thus, many theorists assume that one central feature (and perhaps the function) of emotions is response coherence, variously labeled as response system coherence (Ekman, 1992), organization of response components (Frijda, Ortony, Sonnemans, & Clore, 1992; Scherer, 1984; Witherington et al., 2001), response compoent syndromes (Averill, 1980; Reisenzein, 2000), concordance (Nesse et al., 1985; Wilhelm & Roth, 2001), or organization of response tendencies (Lazarus, 1991; Levenson, 1994).  Second, different emotions should be associated with different patterns of experiential, behavioral, and physiological responding, tailored to meet the demands of different situations (e.g., Lazarus, 1991; Levenson, 1988).  As such, they provide evidence for one of the central tenets of a large number of emotion theories(e.g., Ekman, 1992; Frijda et al., 1992; Lazarus, 1991; Levenson, 1994; Scherer, 1984; Tomkins, 1962),namely, that emotion response systems, including subjective experience, facial behavior, and peripheral physiological reponding, are associated during emotional episodes.  This finding provides some support for functionalist accounts, which have relied on the claim that emotions serve to impose response coherence onemotion response systems (Ekman, 1992; Lazarus, 1991; Levenson, 1994; Plutchik, 1980; Tooby & Cosmides, 1990). 

Most frequent citation words lazarus1991:
response, levenson, coherence, ekman, emotion, different, emotions 
```
It seems that `Mauss2005` cited `lazarus1991` twice as many times as `ekman1999`. Because Dr. Mauss wrote in more length about `lazarus1991` than Dr. Ekman did, the summary is longer. Fortunately, this increased word count has made the final line of the output more useful. This paper appears to be about response coherence in different emotions and mentioned frequently with citations including Levenson and Ekman, who are well-respected emotion theorists. Sounds like `lazarus1991` might be an important paper to read. (Peeking into the PDFs, `lazarus1991` appears to be a book titled _Emotion and Adaptation_. Perhaps I should read the summaries in the output of `magicSynosis("lazarus1991")` to get a better idea of what to expect before reading the book itself.)







